name: schfs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - pyarrow
  - pyyaml
  - jupyter
  - notebook
  - ipykernel
  - matplotlib
  - openpyxl
  - pip
  - pip:
      - pypdf
      - python-docx
      - rapidfuzz
      - chardet
      - tqdm
      - rich
